name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet build "RobotApi.csproj" --configuration Release
      working-directory: ./RobotApi
    - name: Test
      run: dotnet test "RobotApi.Tests.csproj" --configuration Release
      working-directory: ./RobotApi.Tests
